services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Ufo\JsonRpcBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/UfoJsonRpcBundle.php'

    Ufo\JsonRpcBundle\Facade\ZendJsonRpcServerFacade:
        $environment: '%kernel.environment%'

    Ufo\JsonRpcBundle\Security\TokenRpcSecurity:
        $protectedGet: "@=container.hasParameter('ufo_json_rpc.security.protected_get') ? parameter('ufo_json_rpc.security.protected_get') : false"
        $protectedPost: "@=container.hasParameter('ufo_json_rpc.security.protected_post') ? parameter('ufo_json_rpc.security.protected_post') : false"
        $tokenHeaderKey: "@=container.hasParameter('ufo_json_rpc.security.token_key_in_header') ? parameter('ufo_json_rpc.security.token_key_in_header') : 'Ufo-RPC-Token'"

    Ufo\JsonRpcBundle\Security\SimpleTokenValidator:
        $clientsTokens: "@=container.hasParameter('ufo_json_rpc.security.clients_tokens') ? parameter('ufo_json_rpc.security.clients_tokens') : []"
