services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Ufo\JsonRpcBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/UfoJsonRpcBundle.php'

    Ufo\JsonRpcBundle\Facade\ZendJsonRpcServerFacade:
        $environment: '%kernel.environment%'

    Ufo\JsonRpcBundle\Security\TokenRpcSecurity:
        $protectedGet: '%ufo_json_rpc.security.protected_get%'
        $protectedPost: '%ufo_json_rpc.security.protected_post%'
        $tokenHeaderKey: '%ufo_json_rpc.security.token_key_in_header%'

    Ufo\JsonRpcBundle\Security\SimpleTokenValidator:
        $clientsTokens: '%ufo_json_rpc.security.clients_tokens%'
