theme: jekyll-theme-minimal
title: Json-RPC Bundle for Symfony6 Documentation
description: Documentation for Json-RPC Bundle Symfony6

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
    - jekyll-remote-theme # add this line to the plugins list if you already have one

show_downloads: true